version: '3.7'

services:
  api:
    container_name: chapter-notifications-api
    restart: always
    volumes:
      - .:/home/services/chapter-notifications-api
    build: .
    ports:
      - "3000:3000"










